version: '3.8'

services:
  mongodb:
    image:  mongo:4.4
    container_name: accounting_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:latest
    container_name: accounting_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accounting_backend
    command: >
      sh -c "uvicorn accounting_agent.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      # MongoDB
      MONGO_URL: mongodb

      # JWT
      JWT_SECRET: 9a72b2f0e21cbfa0298f5e8d8639080ba240b2fcfd2eb423c348de6cadd08832
      ALGORITHM: HS256

      # Encryption
      ENCRYPTION_KEY: p3IwzOEuR43rEZjBW7_AIPujrMCPbNEhA32ZspO5xkg=

      # Host configuration
      HOST: 0.0.0.0

      # LangGraph Configuration
      LANGGRAPH_URL: http://localhost:8123
      LANGGRAPH_WEBHOOK_URL: https://7aae3367200e.ngrok-free.app/webhook/lol

      # Upload password
      UPLOAD_PASSWORD: "{[QSy%D!2R9v8<CU"
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongo_data: